### ISSUE TITLE
Program not working with custom URL

### ISSUE THREAD

**Issue by aleemladha** [Flangvik/NetLoader#1]
Hi , i noticed the program does not work with a custom url.

![image](https://user-images.githubusercontent.com/26311391/81395606-9e618080-912c-11ea-84c9-d764726a63d2.png)

When i changed the url to the github url, the program works fine .

Thanks to @Mrtn9 for the assist .

![image](https://user-images.githubusercontent.com/26311391/81382935-de6a3880-9117-11ea-8390-43c3f521107a.png)

**Comment by Flangvik** [comment]
Great, resolved!
