### ISSUE TITLE
Getting detected by defender

### ISSUE THREAD

**Issue by iD4rksid3** [Flangvik/NetLoader#2]
While few bins did go undetected with small commands (e.g whoami) most other bins were detected by Windows Defender as shown:

![netload](https://user-images.githubusercontent.com/31139699/83721506-3d09d000-a64c-11ea-8be8-5403f7b2cdd1.jpg)
![netload2](https://user-images.githubusercontent.com/31139699/83721513-42671a80-a64c-11ea-9422-ecc1dfdb657e.jpg)
![netload3](https://user-images.githubusercontent.com/31139699/83721518-45620b00-a64c-11ea-8c68-fa54a38a0ac5.jpg)

**Comment by Arno0x** [comment]
I've been running into the same kind of issue with some of the ".bin" files. Those files get caught by either my proxy AV, or by my local AV.

So I've created my own version of the netloader with some slight modifications, including one which accept XOR encrypted version of the binaries. Works like a charm.

**Comment by iD4rksid3** [comment]
> 
> 
> I've been running into the same kind of issue with some of the ".bin" files. Those files get caught by either my proxy AV, or by my local AV.
> 
> So I've created my own version of the netloader with some slight modifications, including one which accept XOR encrypted version of the binaries. Works like a charm.

can you make a PR ?

**Comment by Flangvik** [comment]
Hey, sorry being late to this. This only happens when you load files from a local path correct? I saw the gist you posted, i will implemented the xor encryption and credit @Arno0x some time soon.

**Comment by Flangvik** [comment]
Closing this as latest commit merged the contribution by  Arno0x

**Comment by Arno0x** [comment]
You did the whole work ! :-) (y)
