### ISSUE TITLE
Still getting detected by Defender

### ISSUE THREAD

**Issue by iD4rksid3** [Flangvik/NetLoader#3]
as with issue #2
![detected](https://user-images.githubusercontent.com/31139699/85676760-f56ce600-b6d7-11ea-8856-51d22ef59638.gif)

**Comment by Flangvik** [comment]
You are loading a non-encrypted detected binary from a local patch, you need to either load it from an online resource (Like SharpCollection) or use the XOR encryption feature within NetLoader. However, the NetLoader project will not receive further signature updated at this time.
